<!--Información del curso-->
<img align="left" style="padding-right:10px;" src="figuras/logo_ciencia_datos.png">

 
<center><h2 style="font-size:2em;color:#840700">   Caso de estudio: Ventas </h4></center>

<br>
<table>
<col width="550">
<col width="450">
<tr>
<td><img src="figuras/ventas.jpg" align="left" style="width:400px"/></td>
<td>

* **Wes McKinney**, empezó a desarrollar Pandas en el año 2008 mientras trabajaba en *AQR Capital* [https://www.aqr.com/] por la necesidad que tenía de una herramienta flexible de alto rendimiento para realizar análisis cuantitativos en datos financieros. 
* Antes de dejar AQR convenció a la administración de la empresa de distribuir esta biblioteca bajo licencia de código abierto.
* **Pandas** es un acrónimo de **PANel DAta analysiS**
   
    
<br>
</td>
</tr>
</table>

## Integrantes
Nombre 1: Leonardo Yeret Ortiz Valle

Nombre 2: Obed Domínguez Mora

Nombre 3: José Manuel Aqué González

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import glob

### Ejercicio

Utilzar los archivos "datos/ventas/*.txt" para contestar las siguientes preguntas. A continuación el código propuesto para obtener el dataframe:

1. Primera alternativa 
```python
files = glob.glob('datos/Ventas/*.txt')
df =  pd.concat((pd.read_csv(file) for file in files))
df=df.dropna(axis='rows',how='any')
df=df[df['Quantity Ordered']!='Quantity Ordered']
df = df.reset_index(drop=True)
df["Quantity Ordered"] = pd.to_numeric(df["Quantity Ordered"], errors="coerce").astype("Int64")
df["Price Each"] = pd.to_numeric(df["Price Each"], errors="coerce")
print(df.shape)
```


2. Segunda alternativa 
```python
files = glob.glob('datos/Ventas/*.txt')
df =  pd.concat((pd.read_csv(file) for file in files))
df = df[pd.to_numeric(df['Order ID'], errors='coerce').notna()]
df = df.reset_index(drop=True)
df["Quantity Ordered"] = df["Quantity Ordered"].astype(int)
df["Price Each"] = df["Price Each"].astype(float)
print(df.shape)
```

In [3]:
files = glob.glob('datos/Ventas/*.txt')
df =  pd.concat((pd.read_csv(file) for file in files))
df=df.dropna(axis='rows',how='any')
df=df[df['Quantity Ordered']!='Quantity Ordered']
df = df.reset_index(drop=True)
df["Quantity Ordered"] = pd.to_numeric(df["Quantity Ordered"], errors="coerce").astype("Int64")
df["Price Each"] = pd.to_numeric(df["Price Each"], errors="coerce")
print(df.shape)

(185950, 6)

In [4]:
files = glob.glob('datos/Ventas/*.txt')
df =  pd.concat((pd.read_csv(file) for file in files))
df = df[pd.to_numeric(df['Order ID'], errors='coerce').notna()]
df = df.reset_index(drop=True)
df["Quantity Ordered"] = df["Quantity Ordered"].astype(int)
df["Price Each"] = df["Price Each"].astype(float)
print(df.shape)

(185950, 6)

<div class="alert alert-success">
    
0. Explicar que hace el código de arriba
    
</div>

In [5]:
df

,Order ID,Product,Quantity Ordered,Price Each,Order Date,Purchase Address
0,278797,Wired Headphones,1,11.99,11/21/19 09:54,"46 Park St, New York City, NY 10001"
1,278798,USB-C Charging Cable,2,11.95,11/17/19 10:03,"962 Hickory St, Austin, TX 73301"
2,278799,Apple Airpods Headphones,1,150.00,11/19/19 14:56,"464 Cherry St, Los Angeles, CA 90001"
3,278800,27in FHD Monitor,1,149.99,11/25/19 22:24,"649 10th St, Seattle, WA 98101"
4,278801,Bose SoundSport Headphones,1,99.99,11/09/19 13:56,"522 Hill St, Boston, MA 02215"
...,...,...,...,...,...,...
185945,209916,Bose SoundSport Headphones,1,99.99,05/08/19 19:15,"235 Center St, Seattle, WA 98101"
185946,209917,Wired Headphones,1,11.99,05/24/19 22:02,"926 9th St, San Francisco, CA 94016"
185947,209918,AAA Batteries (4-pack),2,2.99,05/24/19 17:44,"868 Hickory St, Boston, MA 02215"
185948,209919,USB-C Charging Cable,1,11.95,05/04/19 12:46,"204 Adams St, Seattle, WA 98101"
185949,209920,ThinkPad Laptop,1,999.99,05/18/19 23:07,"43 5th St, Atlanta, GA 30301"

<div class="alert alert-success">
    
1. Encuentre el número de productos que se adquirieron en Los Angeles, CA
    
</div>

In [6]:
df1 = df[df['Purchase Address'].str.contains('Los Angeles, CA')]
df1['Quantity Ordered'].sum()

33289

<div class="alert alert-success">
    
2. ¿Cuántos iPhone se vendieron?

    
</div>

In [7]:
df1 = df[df['Product'].str.contains('iPhone')]
df1['Quantity Ordered'].sum()

6849

<div class="alert alert-success">
    
3. ¿Cuánto fue su ganancia por venta de baterías? 
    
</div>

In [8]:
df1 = df[df['Product'].str.contains('Batteries')]
total = (df1['Quantity Ordered'] * df1['Price Each']).sum()
total

198859.23

<div class="alert alert-success">
    
4. ¿Cuál fue el código postal que más ordenes realizó?

    
</div>

In [9]:
df1 = df['Purchase Address'].groupby(df['Purchase Address'].str.split(',').str[2]).count()
df1 = df1.idxmax()
df1

' CA 94016'

<div class="alert alert-success">
    
5.  a) ¿Cuál fue el producto con más ganancias?
    
    b) ¿Cuál fue el producto con más unidades vendidas?

    
</div>

In [10]:
# a)
df_ganancias = df
df_ganancias['Total ganancia'] = df['Quantity Ordered'] * df['Price Each']
df_ganancias

df_prod = df_ganancias.groupby('Product')['Total ganancia'].sum()
prod = df_prod.idxmax()
prod

'Macbook Pro Laptop'

In [11]:
# b)
df_prod = df.groupby('Product')['Quantity Ordered'].sum()
prod = df_prod.idxmax()
prod

'AAA Batteries (4-pack)'

<div class="alert alert-success">
    
6. ¿Cuales son los 5 productos más vendidos?     
</div>

In [12]:
df_prod = df.groupby('Product')['Quantity Ordered'].sum().sort_values(ascending=False)
df_prod.head()

Product
AAA Batteries (4-pack)      31017
AA Batteries (4-pack)       27635
USB-C Charging Cable        23975
Lightning Charging Cable    23217
Wired Headphones            20557
Name: Quantity Ordered, dtype: int64

<div class="alert alert-success">
    
7.  ¿Cuales son los 5 productos con las ganancias más altas?

    
</div>

In [13]:
df_ganancias.groupby('Product')['Total ganancia'].sum().sort_values(ascending=False).head()

Product
Macbook Pro Laptop        8037600.00
iPhone                    4794300.00
ThinkPad Laptop           4129958.70
Google Phone              3319200.00
27in 4K Gaming Monitor    2435097.56
Name: Total ganancia, dtype: float64

<div class="alert alert-success">
    
8. ¿A qué hora recomendaría mostrar anuncios para maximizar la probabilidad de que el cliente compre un producto?     
</div>

In [14]:
df_tiempo = pd.to_datetime(df['Order Date'])

/tmp/ipykernel_5893/2567862226.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df_tiempo = pd.to_datetime(df['Order Date'])

In [15]:
df_tiempo = pd.DataFrame(df_tiempo)
df_tiempo.set_index(df_tiempo['Order Date'], inplace=True)
df_tiempo

                             Order Date
Order Date
2019-11-21 09:54:00 2019-11-21 09:54:00
2019-11-17 10:03:00 2019-11-17 10:03:00
2019-11-19 14:56:00 2019-11-19 14:56:00
2019-11-25 22:24:00 2019-11-25 22:24:00
2019-11-09 13:56:00 2019-11-09 13:56:00
...                                 ...
2019-05-08 19:15:00 2019-05-08 19:15:00
2019-05-24 22:02:00 2019-05-24 22:02:00
2019-05-24 17:44:00 2019-05-24 17:44:00
2019-05-04 12:46:00 2019-05-04 12:46:00
2019-05-18 23:07:00 2019-05-18 23:07:00

[185950 rows x 1 columns]

<div class="alert alert-success">
     9.   a) ¿Cuál es el día de más ganancias por cada mes?     b) ¿Cuál es el mes con más ganancias y el de menos ganancias?
    
</div>

In [16]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
df['Ganancia'] = df['Quantity Ordered'] * df['Price Each']


df['Dia'] = df['Order Date'].dt.date
df['Mes'] = df['Order Date'].dt.month

# Día de más ganancias por cada mes
ganancias_por_dia = df.groupby('Dia')['Ganancia'].sum().reset_index()
ganancias_por_dia['Mes'] = pd.to_datetime(ganancias_por_dia['Dia']).dt.month

dia_max_por_mes = ganancias_por_dia.loc[ganancias_por_dia.groupby('Mes')['Ganancia'].idxmax()]

# Ordenar de mayor a menor ganancias
dia_max_por_mes = dia_max_por_mes.sort_values(by='Ganancia', ascending=False)

print("Día de más ganancias por cada mes (ordenado de mayor a menor):")
print(dia_max_por_mes)

# Mes con más y menos ganancias
ganancias_por_mes = df.groupby('Mes')['Ganancia'].sum()

mes_max = ganancias_por_mes.idxmax()
mes_min = ganancias_por_mes.idxmin()

print(f"\nEl mes con más ganancias es: {mes_max} con {ganancias_por_mes[mes_max]:,.2f}")
print(f"El mes con menos ganancias es: {mes_min} con {ganancias_por_mes[mes_min]:,.2f}")

/tmp/ipykernel_5893/3975631336.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Order Date'] = pd.to_datetime(df['Order Date'])

Día de más ganancias por cada mes (ordenado de mayor a menor):
            Dia   Ganancia  Mes
337  2019-12-04  166727.69   12
113  2019-04-24  136177.32    4
278  2019-10-06  134384.92   10
327  2019-11-24  130244.50   11
145  2019-05-26  113490.20    5
201  2019-07-21  104283.77    7
80   2019-03-22  102992.11    3
159  2019-06-09   99484.39    6
221  2019-08-10   95160.63    8
38   2019-02-08   94507.13    2
251  2019-09-09   79465.82    9
10   2019-01-11   78414.54    1

El mes con más ganancias es: 12 con 4,613,443.34
El mes con menos ganancias es: 1 con 1,822,256.73

<div class="alert alert-success">
    
10. ¿Cuál fue el producto más comprado en San Francisco, CA?
    
</div>

In [17]:
df = df[df['Purchase Address'].str.contains("San Francisco, CA")]

# Contar cuántas veces se compró cada producto
producto_mas_comprado = df['Product'].value_counts().idxmax()
cantidad = df['Product'].value_counts().max()

print(f"El producto más comprado en San Francisco, CA es: {producto_mas_comprado} con {cantidad} unidades vendidas.")

El producto más comprado en San Francisco, CA es: USB-C Charging Cable con 5368 unidades vendidas.