<!--Información del curso-->
<img align="left" style="padding-right:10px;" src="figuras/logo_ciencia_datos.png">

<center><h1 style="font-size:2em;color:#2467C0"> STR  </h1></center>

<center><h2 style="font-size:2em;color:#840700">   Manipulación de strings </h4></center>

# Librerías

Cargando las bibliotecas que necesitamos

In [19]:
import pandas as pd

#  Lección: Uso de `.str` en Pandas

En Pandas  `.str` permite aplicar operaciones de cadenas de texto **de manera vectorizada** sobre toda una columna (Serie).

Esto evita tener que recorrer fila por fila con bucles `for` y hace el código mucho más eficiente.

## 1. Convertir texto a mayúsculas y minúsculas

Podemos usar `.str.upper()` y `.str.lower()` para normalizar el texto.

In [20]:
df = pd.DataFrame({"nombre": ["Ana", "luis", "MARÍA"]})
df

  nombre
0    Ana
1   luis
2  MARÍA

In [21]:

df["nombre_mayus"] = df["nombre"].str.upper()
df["nombre_minus"] = df["nombre"].str.lower()
df

  nombre nombre_mayus nombre_minus
0    Ana          ANA          ana
1   luis         LUIS         luis
2  MARÍA        MARÍA        maría

##  2. Eliminar espacios en blanco
Con `.str.strip()` quitamos espacios al inicio y final del texto.

In [22]:
df = pd.DataFrame({"palabras": ["  hola ", " mundo  ", " pandas "]})
df

   palabras
0     hola
1   mundo
2   pandas

In [23]:
df["palabras_limpias"] = df["palabras"].str.strip()
df

   palabras palabras_limpias
0     hola              hola
1   mundo              mundo
2   pandas            pandas

##  3. Reemplazar texto
Con `.str.replace()` sustituimos un texto por otro.

In [24]:
df = pd.DataFrame({"frase": ["hola mundo", "pandas es genial"]})
df

              frase
0        hola mundo
1  pandas es genial

In [25]:
df["frase_mod"] = df["frase"].str.replace("mundo", "Python")
df

              frase         frase_mod
0        hola mundo       hola Python
1  pandas es genial  pandas es genial

##  4. Extraer texto usando expresiones regulares (regex)
Con `.str.extract()` podemos obtener partes de un texto.
Ejemplo: extraer el **dominio** de un correo electrónico.

* https://docs.python.org/es/3/howto/regex.html

In [26]:
df = pd.DataFrame({"email": ["ana@mail.com", "luis@uni.mx", "maria@empresa.org"]})
df

               email
0       ana@mail.com
1        luis@uni.mx
2  maria@empresa.org

In [27]:
df["dominio"] = df["email"].str.extract(r'@(.+)$')  # lo que está después del @
df

               email      dominio
0       ana@mail.com     mail.com
1        luis@uni.mx       uni.mx
2  maria@empresa.org  empresa.org

## 5. Dividir texto en columnas
Con `.str.split()` podemos separar un string en partes.

In [28]:
df = pd.DataFrame({"email": ["ana@mail.com", "luis@uni.mx", "maria@empresa.org"]})
df

               email
0       ana@mail.com
1        luis@uni.mx
2  maria@empresa.org

In [29]:
df["email"].str.split('@')

0         [ana, mail.com]
1          [luis, uni.mx]
2    [maria, empresa.org]
Name: email, dtype: object

In [30]:
df["email"].str.split('.')

0         [ana@mail, com]
1          [luis@uni, mx]
2    [maria@empresa, org]
Name: email, dtype: object

In [31]:
df["dominio"] = df["email"].str.split('@').str[1]  # lo que está después del @
df

               email      dominio
0       ana@mail.com     mail.com
1        luis@uni.mx       uni.mx
2  maria@empresa.org  empresa.org

##  6. Buscar si un texto contiene una palabra
Con `.str.contains()` podemos verificar si un texto existe dentro de la cadena.

In [32]:
df = pd.DataFrame({"texto": ["Tres tristes tigres", "tragaban trigo en un trigal",
                              "en tres tristes trastos", "tragaban trigo","treS tristes tigres"]})
df

                         texto
0          Tres tristes tigres
1  tragaban trigo en un trigal
2      en tres tristes trastos
3               tragaban trigo
4          treS tristes tigres

In [33]:
df["texto"].str.contains("tres")

0    False
1    False
2     True
3    False
4    False
Name: texto, dtype: bool

In [34]:
df["texto"].str.contains("tres", case=False) #case sirve para ignorar mayúsculas/minúsculas

0     True
1    False
2     True
3    False
4     True
Name: texto, dtype: bool

In [ ]:
df[ df["texto"].str.contains("tres", case=False)

                     texto
0      Tres tristes tigres
2  en tres tristes trastos
4      treS tristes tigres