<!--Información del curso-->
<img align="left" style="padding-right:10px;" src="figuras/banner_cd.png">

# Proyecto de Machine Learning:  Prediccion de precios de casas

	
Pasos principales que deberá seguir:


1. Mira el panorama general y entienda el problema.
* Obtenga los datos.
* Descubra y visualice los datos para obtener información.
* Prepare los datos para los algoritmos de Machine Learning.
* Seleccione un modelo y realice el entrenamiento (train).
* Afina(fine tune) el modelo.
* Presente su solución.
* Inicie (Launch), monitoree y mantenga su sistema
(https://bit.ly/2Sqtfhl)

## 1. Introducción

#  USA Housing Dataset

El **USA Housing Dataset** contiene información socioeconómica y demográfica de distintas áreas residenciales en Estados Unidos, con el propósito de analizar los factores que influyen en el **precio promedio de las viviendas**.  

Este conjunto de datos es comúnmente utilizado para **modelos de regresión**, **análisis exploratorio de datos (EDA)** y **aprendizaje automático supervisado**, especialmente para ejercicios de predicción de precios inmobiliarios.

---

##  Archivo

- **Ruta:** `USA_Housing.csv`  
- **Tamaño:** 319 KB  
- **Número de registros:** 5001  
- **Número de variables:** 6

---

##  Descripción de las columnas

| Columna | Descripción | Tipo de dato |
|----------|--------------|---------------|
| `Area Income` | Ingreso promedio anual de los residentes en el área | Numérico (float) |
| `Area House Age` | Edad promedio de las viviendas en el área (en años) | Numérico (float) |
| `Area No of Rooms` | Promedio de habitaciones por vivienda en el área | Numérico (float) |
| `Area No of Bedrooms` | Promedio de dormitorios por vivienda en el área | Numérico (float) |
| `Area Population` | Población promedio del área | Numérico (float) |
| `Price` | Precio promedio de las viviendas (variable objetivo) | Numérico (float) |

---

## Objetivo del dataset

El objetivo principal es **predecir el precio de las viviendas (`Price`)** a partir de las características demográficas y estructurales del área.  
Este dataset es ideal para practicar técnicas de:

- Regresión lineal y múltiple  
- Selección y normalización de características  
- Evaluación de modelos predictivos  
- Visualización de correlaciones socioeconómicas  

---

## 2. Obtenga los datos

In [75]:
#Librerias principales
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import seaborn as sns

In [76]:
#Cargar el archivo "datos/uber_train_validation.cvs"
df = pd.read_csv("datos/uber_train_validation.csv")

## 3. Descubra y visualice los datos para obtener información.

In [77]:
# Mostrar los primeras filas
df.head()

,fare_amount,pickup_datetime,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,pickup_year,pickup_month,pickup_weekday,pickup_hour,pickup_season,pickup_period,geo_distance
0,8.1,2010-01-05 12:46:37+00:00,-73.997719,40.741156,-73.976336,40.740022,1,2010,1,1,12,Winter,Afternoon,1.805911
1,4.9,2011-02-05 12:11:00+00:00,-74.010218,40.711418,-74.004135,40.725397,1,2011,2,5,12,Winter,Afternoon,1.636753
2,16.1,2012-03-08 02:13:00+00:00,-73.982152,40.764017,-73.891160,40.746512,1,2012,3,3,2,Spring,Night,7.907627
3,19.3,2011-10-03 22:20:55+00:00,-74.000808,40.728923,-73.979544,40.653311,1,2011,10,0,22,Autumn,Night,8.596692
4,3.5,2013-07-23 19:21:53+00:00,-73.985567,40.723071,-73.991561,40.726360,1,2013,7,1,19,Summer,Evenning,0.623609

In [78]:
#Información general

In [79]:
# Mostrar el número de filas y columnas
df.shape

(158000, 14)

In [80]:
# Mostrar el tipo de variables
df.dtypes

fare_amount          float64
pickup_datetime       object
pickup_longitude     float64
pickup_latitude      float64
dropoff_longitude    float64
dropoff_latitude     float64
passenger_count        int64
pickup_year            int64
pickup_month           int64
pickup_weekday         int64
pickup_hour            int64
pickup_season         object
pickup_period         object
geo_distance         float64
dtype: object

In [81]:
#Graficar todas las variables numericas

### Correlación de variables

In [82]:
df.columns

Index(['fare_amount', 'pickup_datetime', 'pickup_longitude', 'pickup_latitude',
       'dropoff_longitude', 'dropoff_latitude', 'passenger_count',
       'pickup_year', 'pickup_month', 'pickup_weekday', 'pickup_hour',
       'pickup_season', 'pickup_period', 'geo_distance'],
      dtype='object')

In [83]:
#Hacer diagramas de correlación
# Definir una lista llamada atributos  con las siguientes variables : 
#'Area Income', 'Area House Age', 'Area No of Rooms','Area No of Bedrooms', 'Area Population'
from pandas.plotting import scatter_matrix

atributos = ['passenger_count',
       'pickup_year', 'pickup_month', 'pickup_weekday', 'pickup_hour',
       'geo_distance']

# sns.pairplot(df[atributos] , kind="reg",
#                  plot_kws={'scatter_kws': {'color': "#3AA1A8", 'alpha': 0.6}, 
#               'line_kws': {'color': "#EC1313", 'lw': 2}}
#              )  
# plt.show()

In [84]:
#Con seaborn para ver posibles rergesiones lineales

In [85]:
# Matriz correlación númerica y visual
#https://matplotlib.org/tutorials/colors/colormaps.html
#Instalación de seaborn
#pip install seaborn

## 4. Prepare los datos y sus transformadores

In [86]:
#Revisar si hay datos perdidos NaN
df.isnull().sum()

fare_amount          0
pickup_datetime      0
pickup_longitude     0
pickup_latitude      0
dropoff_longitude    0
dropoff_latitude     0
passenger_count      0
pickup_year          0
pickup_month         0
pickup_weekday       0
pickup_hour          0
pickup_season        0
pickup_period        0
geo_distance         0
dtype: int64

In [87]:
#Número de filas

In [88]:
# eliminar datos  perdidos NaN|
df.dropna(inplace=True)

In [89]:
len(df)

158000

###  ColumnTransformer  y pipeline

<img src="figuras/pipeline.jpg" align="middle" style="width:500px;" />

#### Pipeline

La función pipeline permite juntar varios trasformaciones secuenciales que se requieren ejecutar a un conjunto de datos.

**Pipeline(steps=[('titulo trasnformación1', trasnformación1), ('titulo trasnformación2', trasnformación2),...])**

In [90]:
#Modulos importantes
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [91]:
# Crear la lista de  viriables numericas y categoricas
# 'Area Income', 'Area House Age', 'Area No of Rooms', 'Area No of Bedrooms', 'Area Population'
lista_num=['passenger_count',
       'pickup_year', 'pickup_month', 'pickup_weekday', 'pickup_hour',
       'geo_distance']

In [92]:
# Mostrar las columnas del dataframe
df.columns

Index(['fare_amount', 'pickup_datetime', 'pickup_longitude', 'pickup_latitude',
       'dropoff_longitude', 'dropoff_latitude', 'passenger_count',
       'pickup_year', 'pickup_month', 'pickup_weekday', 'pickup_hour',
       'pickup_season', 'pickup_period', 'geo_distance'],
      dtype='object')

In [93]:
# Crear el pipeline de preprocesamiento para datos numéricos y categóricos.
transformacion_num=Pipeline( [  ( 'scaler' , StandardScaler()  )    ] )

#### ColumnTransformer

ColumnTransformer es una clase de scikit-learn que  permite aplicar transformaciones de preparación de datos de forma selectiva.

Por ejemplo,  permite aplicar una transformación específica o secuencia de transformaciones solo a las columnas numéricas, y una secuencia separada de transformaciones solo a las columnas categóricas.

Para usar ColumnTransformer, debe especificar una lista de transformadores.

Cada transformador es una tupla de tres elementos que define el nombre del transformador, la transformación a aplicar y los índices de columna a los que aplicar. Por ejemplo: **(Nombre, objeto, columnas)**

In [94]:
# Definir los transformadores
transformacion = ColumnTransformer(  [ ('num',transformacion_num,lista_num ) ] )

### Preparando las muestras de entrenamiento y prueba

<img  align="middle" style="width:550px;" src="figuras/ml_diagrama3.jpg">

División general de los datos
* **X**: Datos  sin la columna "median_house_value""
* **y**: Datos con la columna "median_house_value"

Muestras de entrenamiento y prueba
* **X_train**: este será el grupo de entrenamiento
* **X_test**: este será el  grupo de prueba
* **y_train**: este será el target para el grupo de entrenamiento
* **y_test**: este será el target para el grupo de prueba

In [95]:
# Crear X (Quitar la columna o campo de "fare_amount")
X=df.drop(['pickup_datetime', 'pickup_longitude', 'pickup_latitude', 'dropoff_longitude', 'dropoff_latitude', 'fare_amount','pickup_season', 'pickup_period'], axis=1)
X.head()

,passenger_count,pickup_year,pickup_month,pickup_weekday,pickup_hour,geo_distance
0,1,2010,1,1,12,1.805911
1,1,2011,2,5,12,1.636753
2,1,2012,3,3,2,7.907627
3,1,2011,10,0,22,8.596692
4,1,2013,7,1,19,0.623609

In [96]:
# Crear y (Valor de de la columna "fare_amount")
y=df["fare_amount"]

In [97]:
# Dividir los datos para entrenamiento y prueba
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42 )

In [98]:
# Revise  el tamaño de cada muestra
print(  len(X) ,  len(X) *0.8 , len(X) *0.2     )

print( len(X_train) )
print( len(X_test) )
print( len(y_test) )
print( len(y_train) )

158000 126400.0 31600.0
126400
31600
31600
126400

# 6 .  Afina(fine tune) el modelo  

# Hyperparámetros clave para `SVR` (Support Vector Regressor, scikit-learn)

El modelo **SVR** (Support Vector Regression) busca ajustar una función que minimiza los errores fuera de un margen de tolerancia (ε), utilizando kernels para modelar relaciones lineales o no lineales.

---

## 1. `kernel`
- **Qué es:** tipo de función que transforma los datos al espacio de mayor dimensión.
- **Efecto:** define la forma del límite de regresión (lineal o no lineal).
- **Probar:**
  - `"linear"` → relaciones simples y proporcionales.  
  - `"poly"` → relaciones polinómicas (ajusta con `degree`).  
  - `"rbf"` → relaciones no lineales suaves (más común).  
  - `"sigmoid"` → menos usado, comportamiento tipo red neuronal.

---

## 2. `C`
- **Qué es:** parámetro de penalización del error.
- **Efecto:** controla el equilibrio entre el ajuste del modelo y la simplicidad.
  - Alto `C` → menor tolerancia a errores → posible sobreajuste.  
  - Bajo `C` → más regularización → posible subajuste.
- **Probar:** `0.1, 1, 10, 100, 1000`

---

## 3. `epsilon`
- **Qué es:** margen de tolerancia dentro del cual los errores no se penalizan.
- **Efecto:** controla la sensibilidad del modelo a pequeños errores.
  - Mayor `epsilon` → menos sensible → más suave.  
  - Menor `epsilon` → más preciso → puede sobreajustar.
- **Probar:** `0.01, 0.05, 0.1, 0.2, 0.5`

---

## 4. `gamma` *(solo aplica a kernels `"rbf"`, `"poly"`, `"sigmoid"`)*
- **Qué es:** define la influencia de cada punto de entrenamiento.
- **Efecto:** controla la curvatura de la superficie de decisión.
  - Alto `gamma` → curvas más ajustadas → posible sobreajuste.  
  - Bajo `gamma` → curvas más suaves → posible subajuste.
- **Probar:** `"scale"`, `"auto"`, `0.01, 0.1, 1, 10`

---

## 5. `degree`
- **Qué es:** grado del polinomio en el kernel `"poly"`.
- **Efecto:** solo tiene efecto si `kernel='poly'`.
- **Probar:** `2, 3, 4, 5`

In [99]:
#Aplicar el modelo RandomForestRegressor
from sklearn.svm import LinearSVR

In [100]:
#1. Nombrar una variable para nuestro modelo
SVM_regression = LinearSVR()

In [101]:
SVM_regression.get_params()

{'C': 1.0,
 'dual': 'auto',
 'epsilon': 0.0,
 'fit_intercept': True,
 'intercept_scaling': 1.0,
 'loss': 'epsilon_insensitive',
 'max_iter': 1000,
 'random_state': None,
 'tol': 0.0001,
 'verbose': 0}

In [102]:
#2. Definir el Pipeline : Transformación  + modelo
modelo_SVM = Pipeline( [ ('transformacion',transformacion) ,
                        ('SVM_regression', SVM_regression )  ] )

In [103]:
# Utilizamos la función GridSearchCV para encontrar los valores optimos
from sklearn.model_selection import GridSearchCV

In [ ]:
#Definición de posibles parametros
C = [1, 10, 100]
epsilon = [0.0001, 0.0005, 0.001]

parametros = {
    'SVM_regression__C': C,
    'SVM_regression__epsilon': epsilon
}

In [105]:
#Definicion del grid de busqueda
grid_SVM = GridSearchCV( estimator=modelo_SVM,
                        param_grid=parametros,
                        cv=5,
                        n_jobs=-1,
                        scoring='neg_mean_squared_error' ,
                        verbose=2)

In [106]:
# Ajuste del modelo usando todas las posibles combinaciones de parametros 
grid_SVM.fit(X,y)

Fitting 5 folds for each of 12 candidates, totalling 60 fits

c:\Users\aquek\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('transformacion',
                                        ColumnTransformer(transformers=[('num',
                                                                         Pipeline(steps=[('scaler',
                                                                                          StandardScaler())]),
                                                                         ['passenger_count',
                                                                          'pickup_year',
                                                                          'pickup_month',
                                                                          'pickup_weekday',
                                                                          'pickup_hour',
                                                                          'geo_distance'])])),
                                       ('SVM_regression', LinearSVR())]),
             n_jobs=-1,
             param_grid={'SVM_regression__C': [100, 1000, 10000, 15000],
                         'SVM_regression__epsilon': [0.001, 0.01, 0.1]},
             scoring='neg_mean_squared_error', verbose=2)

In [107]:
# Mostrar la mejor combinación
print( grid_SVM.best_params_ )

{'SVM_regression__C': 100, 'SVM_regression__epsilon': 0.001}

**Encontramos los nuevos valores de la media y desviación estándar**

In [ ]:
#1 Ajustar el modelo con los nuevos parametros 
SVM_regression_tunned = LinearSVR(C=100, epsilon=0.001)

In [109]:
SVM_regression_tunned.get_params()

{'C': 1000,
 'dual': 'auto',
 'epsilon': 0.01,
 'fit_intercept': True,
 'intercept_scaling': 1.0,
 'loss': 'epsilon_insensitive',
 'max_iter': 1000,
 'random_state': None,
 'tol': 0.0001,
 'verbose': 0}

In [110]:
#2. Definir el Pipeline : Transformación  + modelo
modelo_SVM_tunned = Pipeline( [  ('transformacion', transformacion   ) ,
                                     ('SVM_regression_tunned',SVM_regression_tunned) ]  )

In [111]:
#3. Ajustar el modelo
modelo_SVM_tunned.fit(X,y)

c:\Users\aquek\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

Pipeline(steps=[('transformacion',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('scaler',
                                                                   StandardScaler())]),
                                                  ['passenger_count',
                                                   'pickup_year',
                                                   'pickup_month',
                                                   'pickup_weekday',
                                                   'pickup_hour',
                                                   'geo_distance'])])),
                ('SVM_regression_tunned', LinearSVR(C=1000, epsilon=0.01))])

In [112]:
from sklearn.model_selection import cross_val_score

# 4. Calcular el score con la validación cruzada CV=5
cv_SVM_tunned = cross_val_score(modelo_SVM_tunned, X, y, cv=5, scoring='neg_mean_squared_error')
cv_SVM_tunned

c:\Users\aquek\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\aquek\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\aquek\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\aquek\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
c:\Users\aquek\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\svm\_base.py:1250: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(

array([-30.85185803, -32.06363473, -40.79797604, -38.84832964,
       -39.53403013])

In [113]:
# 5. Realizar el cambio de signo y sacar la raiz
error_SVM_tunned = np.sqrt(-cv_SVM_tunned)
error_SVM_tunned

array([5.55444489, 5.66247602, 6.38732934, 6.23284282, 6.28760925])

In [114]:
# 6. Mostrar el resultado usando la funcion display_scores
media_error_SVM_tunned = np.mean(error_SVM_tunned)
std_error_SVM_tunned = np.std(error_SVM_tunned)
print("Media :", media_error_SVM_tunned)
print("Desviación estándar :", std_error_SVM_tunned)

Media : 6.024940465092969
Desviación estándar : 0.34533767048263

# Guardar el modelo entrenado

In [115]:
import joblib

In [116]:
joblib.dump(modelo_SVM_tunned, 'modelos/modelo_UBER_SVM_tunned.joblib')

['modelos/modelo_UBER_SVM_tunned.joblib']