<!--Información del curso-->
<img align="left" style="padding-right:10px;" src="figuras/banner_cd.png">

In [8]:
import joblib
import glob
import os
import numpy as np
import pandas as pd
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [9]:
# 1. Carga tus datos de prueba
df=pd.read_csv("datos/USA_Housing_Test.txt")
df.dropna(inplace=True)
df.head(2)

,Area Income,Area House Age,Area No of Rooms,Area No of Bedrooms,Area Population,Price
0,83444.99369,5.310037,6.029292,2.43,44807.98836,1514555.082
1,76609.91724,3.770548,6.700456,3.21,55430.31157,1214689.184

In [10]:
X_test =df.drop("Price", axis=1)
X_test.head(2)

,Area Income,Area House Age,Area No of Rooms,Area No of Bedrooms,Area Population
0,83444.99369,5.310037,6.029292,2.43,44807.98836
1,76609.91724,3.770548,6.700456,3.21,55430.31157

In [11]:
y_test=df[ "Price"]
y_test.head(2)

0    1514555.082
1    1214689.184
Name: Price, dtype: float64

In [12]:
#modelos
ruta_modelos = "modelos/"  # cámbiala a tu carpeta
archivos_modelos = glob.glob(os.path.join(ruta_modelos, "*.joblib"))

In [13]:
resultados = []
for modelo_path in archivos_modelos:
    # nombre del modelo a partir del archivo
    nombre_modelo = os.path.basename(modelo_path).replace(".joblib", "")
    
    # 2. cargar modelo
    modelo = joblib.load(modelo_path)
    
    # 3. predecir
    y_pred = modelo.predict(X_test)
    
    # 4. métricas
    r2 = r2_score(y_test, y_pred)
    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    
    resultados.append({
        "modelo": nombre_modelo,
        "r2": r2,
        "MAE": mae,
        "MSE": mse,
        "RMSE": rmse
    })

# 5. Pasar a DataFrame para comparar
df_resultados = pd.DataFrame(resultados).sort_values(by="r2", ascending=False)
print(df_resultados)

              modelo        r2           MAE           MSE           RMSE
1  modelo_MLP_tunned  0.911773  82528.562645  1.066168e+10  103255.419544
0   modelo_RF_tunned  0.877634  96339.730673  1.478712e+10  121602.304954

In [7]:
# Cargar el modelo
modelo = joblib.load("modelos/MEJOR-MODELO. joblib")

# Hacer las predicciones
y_pred = modelo.predict(X_test)

# Guardar las predicciones en un archivo CSV
pd.DataFrame(y_pred, columns=["Prediccion"]).to_csv("predicciones_ENRIQUECAMACHO.csv", index=False)

print("Archivo guardado correctamente.")

FileNotFoundError: [Errno 2] No such file or directory: 'modelos/MEJOR-MODELO. joblib'